// Generated by CoffeeScript 1.10.0
(function() {
  var applist, entries, i, legend, len, markLabels, ul;

  $(window).scroll(function() {
    return $("#sidenav").css("top", Math.max(40, 100 - $(this).scrollTop()));
  });

  markLabels = function(collection, inline) {
    var entries, i, len, li, results, suffix;
    entries = collection.find("li");
    suffix = inline ? " label__inline" : "";
    console.log(entries);
    results = [];
    for (i = 0, len = entries.length; i < len; i++) {
      li = entries[i];
      console.log(li);
      if (li.getElementsByTagName("strong").length && li.getElementsByTagName("em").length) {
        results.push(li.className = "label label__esspaid" + suffix);
      } else if ((li.getElementsByTagName("strong").length)) {
        results.push(li.className = "label label__ess" + suffix);
      } else if ((li.getElementsByTagName("em").length)) {
        results.push(li.className = "label label__paid" + suffix);
      } else {
        results.push(li.className = "label label__free" + suffix);
      }
    }
    return results;
  };

  window.onload = function() {
    $('.programs ul > li').click(function() {
      return $('.programs').toggleClass('active');
    });
    return $('.websites ul > li').click(function() {
      return $('.websites').toggleClass('active');
    });
  };

  applist = $(".app-container");

  legend = $(".top-wrapper__legend");

  markLabels(applist, false);

  markLabels(legend, true);

  entries = applist.find("ul");

  for (i = 0, len = entries.length; i < len; i++) {
    ul = entries[i];
    ul.className = "label-container";
  }

}).call(this);
