// Generated by CoffeeScript 1.10.0
(function() {
  var markLabels;

  $(window).scroll(function() {
    return $("#sidenav").css("top", Math.max(40, 100 - $(this).scrollTop()));
  });

  $("#sidenav ul>li>a").click(function() {
    return $("#sidenav ul>li>ul").addClass('selected');
  });

  markLabels = function(collection, inline) {
    var entries, i, len, li, results, suffix;
    entries = collection.getElementsByTagName("li");
    suffix = inline ? " label__inline" : "";
    console.log(entries);
    results = [];
    for (i = 0, len = entries.length; i < len; i++) {
      li = entries[i];
      console.log(li);
      if (li.getElementsByTagName("strong").length && li.getElementsByTagName("em").length) {
        results.push(li.className = "label label__esspaid" + suffix);
      } else if ((li.getElementsByTagName("strong").length)) {
        results.push(li.className = "label label__ess" + suffix);
      } else if ((li.getElementsByTagName("em").length)) {
        results.push(li.className = "label label__paid" + suffix);
      } else {
        results.push(li.className = "label label__free" + suffix);
      }
    }
    return results;
  };

  window.onload = function() {
    var applist, entries, i, legend, len, results, ul;
    applist = $(".app-container");
    legend = $(".top-wrapper__legend");
    markLabels(applist[0], false);
    markLabels(legend[0], true);
    entries = applist[0].getElementsByTagName("ul");
    results = [];
    for (i = 0, len = entries.length; i < len; i++) {
      ul = entries[i];
      results.push(ul.className = "label-container");
    }
    return results;
  };

}).call(this);
